version: 0.2
phases:
build:
  install:
    commands:
      - echo Build started on `date`
      - sudo yum update -y
      - sudo yum install java-17-openjdk-devel
      - sudo yum install docker -y
      - sudo service docker start
      - mvn test
pre_build:
  - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
post_build:
  commands:
    - echo Build completed on `date`
    - mvn package
artifacts:
  files:
    - target/spring-boot-basic-example-0.0.1-SNAPSHOT.jar