version: 0.2
phases:
  pre_build:
    commands:
      - echo Test started on `date`
      - mvn package
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/spring-boot-basic-example-0.0.1-SNAPSHOT.jar
