version = 0.1
[default.deploy.parameters]
stack_name = "spring-boot-basic-example"
resolve_s3 = true
s3_prefix = "spring-boot-basic-example"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Stage=\"develop\""
