AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30

Resources:
  SpringBootBasicExample:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.example.awsdemo.config.AWSStreamHandler::handleRequest
      Runtime: java17
      AutoPublishAlias: dev
      SnapStart:
        ApplyOn: PublishedVersions
      Architectures:
        - x86_64
      MemorySize: 2048
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        Employee:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY