version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::388362140757:user/aws-sam-cli-managed-development-pipel-PipelineUser-KT14ZQDJ7GK1"
permissions_provider = "AWS IAM"

[development.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::388362140757:role/aws-sam-cli-managed-developme-PipelineExecutionRole-qK6G6vLWscc4"
cloudformation_execution_role = "arn:aws:iam::388362140757:role/aws-sam-cli-managed-devel-CloudFormationExecutionRo-Y11GJA4Z3lDJ"
artifacts_bucket = "aws-sam-cli-managed-development-p-artifactsbucket-4x50jggtuwvl"
image_repository = ""
region = "us-east-1"
