server:
  port: 5000

cloud:
    aws:
      region:
        static: us-east-1
        auto: false
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRETE_ACCESS_KEY}